apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Blog-App
  description: This is a dummy Node.js app
  annotations:
    backstage.io/managed-by-location: https://github.com/heraldofsolace/nodejs-server-server/blob/final/catalog-info.yaml
  tags:
    - node

spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - blog-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: blog-api
  description: The Blog API
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: https://github.com/heraldofsolace/nodejs-server-server/blob/final/api/swagger.yaml